import type { IResponse } from '@app/shared/models/common';
import type { ICenterInfo } from '@app/shared/models/dto/center/center-info.interface';

export const centerList: IResponse<ICenterInfo[]> = {
  developMode: true,
  Status: 0,
  message: {
    data: [
      {
        uuid: null,
        mcntCnt: 122088,
        mcntMcntCnt: 122087,
        recipeType: 1,
        mcntName: 'تست API',
        mcntTitle: ' مطب پزشكي  درمانگاه تست API',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 4,
        hchrDesc: 'پارس تامين',
        hchrDescParent: 'پارس تامين',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6622035,
        hchrChr: 851,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 128143,
        mcntMcntCnt: 128142,
        recipeType: 1,
        mcntName: 'مطب پزشكي API2',
        mcntTitle: ' مطب پزشكي  درمانگاه مطب پزشكي API2',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 4,
        hchrDesc: 'پارس تامين',
        hchrDescParent: 'پارس تامين',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6626631,
        hchrChr: 851,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 35784,
        mcntMcntCnt: 35765,
        recipeType: 1,
        mcntName: '17شهريور',
        mcntTitle: ' مطب پزشكي  درمانگاه 17شهريور',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6399200,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 53276,
        mcntMcntCnt: 53274,
        recipeType: 1,
        mcntName: 'پاشائي',
        mcntTitle: ' مطب پزشكي  درمانگاه پاشائي',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'آذربايجان شرقي',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6631163,
        hchrChr: 43,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 93643,
        mcntMcntCnt: 93642,
        recipeType: 1,
        mcntName: 'امامي راد (رسول اعظم)',
        mcntTitle: ' مطب پزشكي  درمانگاه امامي راد (رسول اعظم)',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'فارس',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6645481,
        hchrChr: 32,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 48941,
        mcntMcntCnt: 6179,
        recipeType: 1,
        mcntName: 'انصار فسا',
        mcntTitle: ' مطب پزشكي  درمانگاه انصار فسا',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'فارس',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6474054,
        hchrChr: 32,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 40836,
        mcntMcntCnt: 40825,
        recipeType: 1,
        mcntName: 'بقيه الله اعظم',
        mcntTitle: ' مطب پزشكي  بيمارستان بقيه الله اعظم',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8357492,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 47568,
        mcntMcntCnt: 47567,
        recipeType: 1,
        mcntName: 'بقيه اله',
        mcntTitle: ' مطب پزشكي  بيمارستان بقيه اله',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'بوشهر',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8357483,
        hchrChr: 31,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 32667,
        mcntMcntCnt: 22830,
        recipeType: 1,
        mcntName: 'بهداري امام حسين شاهين شهر',
        mcntTitle: ' مطب پزشكي  درمانگاه بهداري امام حسين شاهين شهر',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'اصفهان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6407060,
        hchrChr: 13,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 118858,
        mcntMcntCnt: 118813,
        recipeType: 1,
        mcntName: 'بيمارستان سردارقاسم سليماني (ورزنه)',
        mcntTitle: ' مطب پزشكي  بيمارستان بيمارستان سردارقاسم سليماني (ورزنه)',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'اصفهان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6499336,
        hchrChr: 13,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 31470,
        mcntMcntCnt: 24265,
        recipeType: 1,
        mcntName: 'بيمارستان كاشاني',
        mcntTitle: ' مطب پزشكي  بيمارستان بيمارستان كاشاني',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'اصفهان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6617101,
        hchrChr: 13,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 2676,
        mcntMcntCnt: null,
        recipeType: 1,
        mcntName: 'جهانگير بهمني بهلولي زرقان',
        mcntTitle: ' مطب پزشكي  جهانگير بهمني بهلولي زرقان',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'فارس',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6645383,
        hchrChr: 32,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 46122,
        mcntMcntCnt: 22887,
        recipeType: 1,
        mcntName: 'حضرت ابوالفضل (ع)',
        mcntTitle: ' مطب پزشكي  درمانگاه حضرت ابوالفضل (ع)',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'قم',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6621621,
        hchrChr: 11,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 21065,
        mcntMcntCnt: 3417,
        recipeType: 1,
        mcntName: 'خاتم الانبيا',
        mcntTitle: ' مطب پزشكي  بيمارستان خاتم الانبيا',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'هرمزگان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6655733,
        hchrChr: 18,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 120366,
        mcntMcntCnt: 120365,
        recipeType: 1,
        mcntName: 'خاتم الانبيا',
        mcntTitle: ' مطب پزشكي  درمانگاه خاتم الانبيا',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'بوشهر',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6497447,
        hchrChr: 31,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 104368,
        mcntMcntCnt: null,
        recipeType: 1,
        mcntName: 'سارا فرهادي',
        mcntTitle: ' مطب پزشكي  سارا فرهادي',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6651127,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 53568,
        mcntMcntCnt: 6301,
        recipeType: 1,
        mcntName: 'شبكه بهداشت فسا',
        mcntTitle: ' مطب پزشكي  درمانگاه شبكه بهداشت فسا',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'فارس',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6640805,
        hchrChr: 32,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 102074,
        mcntMcntCnt: 102073,
        recipeType: 1,
        mcntName: 'شهريار',
        mcntTitle: ' مطب پزشكي  درمانگاه شهريار',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'قم',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6624412,
        hchrChr: 11,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 39447,
        mcntMcntCnt: 39422,
        recipeType: 1,
        mcntName: 'شهيد چمران',
        mcntTitle: ' مطب پزشكي  بيمارستان شهيد چمران',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6408078,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 102177,
        mcntMcntCnt: 102176,
        recipeType: 1,
        mcntName: 'شهيد بروجردي(شهداي مدافع حرم سابق)',
        mcntTitle: ' مطب پزشكي  درمانگاه شهيد بروجردي(شهداي مدافع حرم سابق)',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6653952,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 10901,
        mcntMcntCnt: 4700,
        recipeType: 1,
        mcntName: 'صدوقي',
        mcntTitle: ' مطب پزشكي  درمانگاه صدوقي',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'يزد',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6503785,
        hchrChr: 29,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 126132,
        mcntMcntCnt: 126129,
        recipeType: 1,
        mcntName: 'طبيب',
        mcntTitle: ' مطب پزشكي  درمانگاه طبيب',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'خوزستان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6619424,
        hchrChr: 51,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 32684,
        mcntMcntCnt: 32682,
        recipeType: 1,
        mcntName: 'فرهنگيان منطقه2',
        mcntTitle: ' مطب پزشكي  درمانگاه فرهنگيان منطقه2',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6452549,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 42838,
        mcntMcntCnt: 42836,
        recipeType: 1,
        mcntName: 'قريب',
        mcntTitle: ' مطب پزشكي  درمانگاه قريب',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'آذربايجان شرقي',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6621767,
        hchrChr: 43,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 108705,
        mcntMcntCnt: 108704,
        recipeType: 1,
        mcntName: 'كلينيك عمومي پرتوي مهر',
        mcntTitle: ' مطب پزشكي  درمانگاه كلينيك عمومي پرتوي مهر',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'اصفهان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6627046,
        hchrChr: 13,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 22281,
        mcntMcntCnt: 22129,
        recipeType: 1,
        mcntName: 'مجتمع آموزشي ،درماني وپژوهشي پيامبراعظم(ص)',
        mcntTitle: ' مطب پزشكي  بيمارستان مجتمع آموزشي ،درماني وپژوهشي پيامبراعظم(ص)',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'هرمزگان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6647156,
        hchrChr: 18,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 120112,
        mcntMcntCnt: 120070,
        recipeType: 1,
        mcntName: 'مجرد',
        mcntTitle: ' مطب پزشكي  بيمارستان مجرد',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6489012,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 127454,
        mcntMcntCnt: null,
        recipeType: 1,
        mcntName: 'منصوره حسني تبار',
        mcntTitle: ' مطب پزشكي  منصوره حسني تبار',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'لرستان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 3167644,
        hchrChr: 50,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 91039,
        mcntMcntCnt: null,
        recipeType: 1,
        mcntName: 'مهران قاضي سعيدي',
        mcntTitle: ' مطب پزشكي  مهران قاضي سعيدي',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'خراسان شمالي',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6629222,
        hchrChr: 90,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 38621,
        mcntMcntCnt: 38610,
        recipeType: 1,
        mcntName: 'هما',
        mcntTitle: ' مطب پزشكي  درمانگاه هما',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8373654,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 40203,
        mcntMcntCnt: 40173,
        recipeType: 1,
        mcntName: 'وليعصر ناجا 1',
        mcntTitle: ' مطب پزشكي  بيمارستان وليعصر ناجا 1',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8363582,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 105843,
        mcntMcntCnt: 105739,
        recipeType: 1,
        mcntName: ' *** مركز تست***',
        mcntTitle: ' مطب پزشكي  درمانگاه  *** مركز تست***',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 999456,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 67606,
        mcntMcntCnt: null,
        recipeType: 1,
        mcntName: 'الهه علي پناهي',
        mcntTitle: ' مطب پزشكي  الهه علي پناهي',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8342060,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 122088,
        mcntMcntCnt: 122087,
        recipeType: 1,
        mcntName: 'تست API',
        mcntTitle: ' مطب پزشكي  درمانگاه تست API',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6500784,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 41216,
        mcntMcntCnt: 41214,
        recipeType: 1,
        mcntName: 'حسيني مهر',
        mcntTitle: ' مطب پزشكي  بيمارستان حسيني مهر',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6674251,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 15478,
        mcntMcntCnt: 14015,
        recipeType: 1,
        mcntName: 'دارالشفا خيريه امام صادق',
        mcntTitle: ' مطب پزشكي  درمانگاه دارالشفا خيريه امام صادق',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6635865,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 115718,
        mcntMcntCnt: null,
        recipeType: 1,
        mcntName: 'غيرطرف قرارداد (ويزيت آزاد)',
        mcntTitle: ' مطب پزشكي  غيرطرف قرارداد (ويزيت آزاد)',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8369930,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 120112,
        mcntMcntCnt: 120070,
        recipeType: 1,
        mcntName: 'مجرد',
        mcntTitle: ' مطب پزشكي  بيمارستان مجرد',
        centerType: 1,
        centerTypeDesc: 'مطب پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 5034540,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 122089,
        mcntMcntCnt: 122087,
        recipeType: 2,
        mcntName: 'تست API',
        mcntTitle: ' داروخانه  درمانگاه تست API',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 4,
        hchrDesc: 'پارس تامين',
        hchrDescParent: 'پارس تامين',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6644564,
        hchrChr: 851,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 41548,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: '13آبان',
        mcntTitle: ' داروخانه  13آبان',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8363576,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 42718,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: '29 فروردين',
        mcntTitle: ' داروخانه  29 فروردين',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6474307,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 124962,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'اديبان(حسن)',
        mcntTitle: ' داروخانه  اديبان(حسن)',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6634723,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 6481,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'اما م جعفر صادق',
        mcntTitle: ' داروخانه  اما م جعفر صادق',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'کهکيلويه و بويراحمد',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6500095,
        hchrChr: 33,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 48943,
        mcntMcntCnt: 6179,
        recipeType: 2,
        mcntName: 'انصار فسا',
        mcntTitle: ' داروخانه  درمانگاه انصار فسا',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'فارس',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 3167119,
        hchrChr: 32,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 47571,
        mcntMcntCnt: 47567,
        recipeType: 2,
        mcntName: 'بقيه اله',
        mcntTitle: ' داروخانه  بيمارستان بقيه اله',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'بوشهر',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8357486,
        hchrChr: 31,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 98450,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'بني جمالي',
        mcntTitle: ' داروخانه  بني جمالي',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6635095,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 30113,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'ثامن (شبانه روزي)',
        mcntTitle: ' داروخانه  ثامن (شبانه روزي)',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6417564,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 119125,
        mcntMcntCnt: 11699,
        recipeType: 2,
        mcntName: 'خاتم الانبياء(ص)(فوق تخصصي چشم-مشهد)',
        mcntTitle: ' داروخانه  بيمارستان خاتم الانبياء(ص)(فوق تخصصي چشم-مشهد)',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'خراسان رضوي',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6635966,
        hchrChr: 54,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 49369,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'خاتم انبياء زاغمرز',
        mcntTitle: ' داروخانه  خاتم انبياء زاغمرز',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'مازندران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6644491,
        hchrChr: 17,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 28364,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'دانشگاه شماره1',
        mcntTitle: ' داروخانه  دانشگاه شماره1',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'هرمزگان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6655464,
        hchrChr: 18,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 108197,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'رازي مدد ايران',
        mcntTitle: ' داروخانه  رازي مدد ايران',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6654183,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 24648,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'زهراوي',
        mcntTitle: ' داروخانه  زهراوي',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6674311,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 92723,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'سيد محمد موسوي نيا',
        mcntTitle: ' داروخانه  سيد محمد موسوي نيا',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'لرستان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6643838,
        hchrChr: 50,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 83976,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'شبانه روزي زيباشهر',
        mcntTitle: ' داروخانه  شبانه روزي زيباشهر',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'هرمزگان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6639405,
        hchrChr: 18,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 67120,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'شفيعي محسن',
        mcntTitle: ' داروخانه  شفيعي محسن',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'خراسان رضوي',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6640806,
        hchrChr: 54,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 33756,
        mcntMcntCnt: 33711,
        recipeType: 2,
        mcntName: 'شهيد صنيع خاني',
        mcntTitle: ' داروخانه  درمانگاه شهيد صنيع خاني',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6649973,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 84016,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'صادقي كوپائي',
        mcntTitle: ' داروخانه  صادقي كوپائي',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اصفهان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6658964,
        hchrChr: 13,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 113597,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'صفايي',
        mcntTitle: ' داروخانه  صفايي',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'مرکزي',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 3167293,
        hchrChr: 27,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 118982,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'ظهراب زاده',
        mcntTitle: ' داروخانه  ظهراب زاده',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'مازندران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6638900,
        hchrChr: 17,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 119107,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'عبدالهي',
        mcntTitle: ' داروخانه  عبدالهي',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'البرز',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8363581,
        hchrChr: 57,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 1738,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'غلامرضا حسيني',
        mcntTitle: ' داروخانه  غلامرضا حسيني',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'فارس',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6484665,
        hchrChr: 32,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 6797,
        mcntMcntCnt: 3572,
        recipeType: 2,
        mcntName: 'فاطمه الزهرا',
        mcntTitle: ' داروخانه  درمانگاه فاطمه الزهرا',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'يزد',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6655484,
        hchrChr: 29,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 4049,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'فريدون آريان',
        mcntTitle: ' داروخانه  فريدون آريان',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'فارس',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6654482,
        hchrChr: 32,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 104956,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'قربانيان(آناهيتا)',
        mcntTitle: ' داروخانه  قربانيان(آناهيتا)',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6674315,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 15802,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'قلي پور',
        mcntTitle: ' داروخانه  قلي پور',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'بوشهر',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6671141,
        hchrChr: 31,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 87151,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'كريمي نژاد(كميل)',
        mcntTitle: ' داروخانه  كريمي نژاد(كميل)',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 3167118,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 6101,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'كلانتري',
        mcntTitle: ' داروخانه  كلانتري',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'بوشهر',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8384360,
        hchrChr: 31,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 9419,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'محسني',
        mcntTitle: ' داروخانه  محسني',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'قزوين',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6491037,
        hchrChr: 25,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 122851,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'مريم كرمعلي',
        mcntTitle: ' داروخانه  مريم كرمعلي',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'همدان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8365531,
        hchrChr: 38,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 36711,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'مهاجر',
        mcntTitle: ' داروخانه  مهاجر',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'مازندران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6512134,
        hchrChr: 17,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 115190,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'ميلاني زاده(سروش)',
        mcntTitle: ' داروخانه  ميلاني زاده(سروش)',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'خراسان رضوي',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 3173557,
        hchrChr: 54,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 112949,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'نويد(مجدآبادي)',
        mcntTitle: ' داروخانه  نويد(مجدآبادي)',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6676554,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 37314,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'نوين',
        mcntTitle: ' داروخانه  نوين',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6635086,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 40185,
        mcntMcntCnt: 40173,
        recipeType: 2,
        mcntName: 'وليعصر ناجا 1',
        mcntTitle: ' داروخانه  بيمارستان وليعصر ناجا 1',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8354673,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 40185,
        mcntMcntCnt: 40173,
        recipeType: 2,
        mcntName: 'وليعصر ناجا 1',
        mcntTitle: ' داروخانه  بيمارستان وليعصر ناجا 1',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'هرمزگان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6455053,
        hchrChr: 18,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 106863,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'الي',
        mcntTitle: ' داروخانه  الي',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8365535,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 33831,
        mcntMcntCnt: 26439,
        recipeType: 2,
        mcntName: 'امام خميني خمين',
        mcntTitle: ' داروخانه  بيمارستان امام خميني خمين',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6649739,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 82955,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'جلال زاده(سيده منيره)',
        mcntTitle: ' داروخانه  جلال زاده(سيده منيره)',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6635850,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 46973,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'حسيني مهر 46973 (مركز تستي براي كاربران سازمان)',
        mcntTitle: ' داروخانه  حسيني مهر 46973 (مركز تستي براي كاربران سازمان)',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 54524,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 105740,
        mcntMcntCnt: 105739,
        recipeType: 2,
        mcntName: 'ساخد',
        mcntTitle: ' داروخانه  درمانگاه ساخد',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8368234,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 11452,
        mcntMcntCnt: null,
        recipeType: 2,
        mcntName: 'سعيد حقگو',
        mcntTitle: ' داروخانه  سعيد حقگو',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6635581,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 120071,
        mcntMcntCnt: 120070,
        recipeType: 2,
        mcntName: 'مجرد',
        mcntTitle: ' داروخانه  بيمارستان مجرد',
        centerType: 2,
        centerTypeDesc: 'داروخانه',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8342039,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 52695,
        mcntMcntCnt: 52673,
        recipeType: 3,
        mcntName: 'آذربايجان',
        mcntTitle: ' آزمايشگاه  بيمارستان آذربايجان',
        centerType: 3,
        centerTypeDesc: 'آزمايشگاه',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'آذربايجان غربي',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6642003,
        hchrChr: 44,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 47569,
        mcntMcntCnt: 47567,
        recipeType: 3,
        mcntName: 'بقيه اله',
        mcntTitle: ' آزمايشگاه  بيمارستان بقيه اله',
        centerType: 3,
        centerTypeDesc: 'آزمايشگاه',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'بوشهر',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8357484,
        hchrChr: 31,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 70728,
        mcntMcntCnt: null,
        recipeType: 3,
        mcntName: 'جواد نشاط',
        mcntTitle: ' آزمايشگاه  جواد نشاط',
        centerType: 3,
        centerTypeDesc: 'آزمايشگاه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'فارس',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6653246,
        hchrChr: 32,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 14118,
        mcntMcntCnt: null,
        recipeType: 3,
        mcntName: 'سينا رشت ( پروين ستاري و سيامك گرانمايه )',
        mcntTitle: ' آزمايشگاه  سينا رشت ( پروين ستاري و سيامك گرانمايه )',
        centerType: 3,
        centerTypeDesc: 'آزمايشگاه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'گيلان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8369110,
        hchrChr: 20,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 71271,
        mcntMcntCnt: null,
        recipeType: 3,
        mcntName: 'قصر (پاتوبيولوژي)',
        mcntTitle: ' آزمايشگاه  قصر (پاتوبيولوژي)',
        centerType: 3,
        centerTypeDesc: 'آزمايشگاه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6629769,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 78184,
        mcntMcntCnt: null,
        recipeType: 3,
        mcntName: 'آزمايشگاه طبي123',
        mcntTitle: ' آزمايشگاه  آزمايشگاه طبي123',
        centerType: 3,
        centerTypeDesc: 'آزمايشگاه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8363580,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 77934,
        mcntMcntCnt: null,
        recipeType: 3,
        mcntName: 'از ميكروب تستي',
        mcntTitle: ' آزمايشگاه  از ميكروب تستي',
        centerType: 3,
        centerTypeDesc: 'آزمايشگاه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8395964,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 46972,
        mcntMcntCnt: null,
        recipeType: 3,
        mcntName: 'حسيني مهر 46972 (مركز تستي براي كاربران سازمان)',
        mcntTitle: ' آزمايشگاه  حسيني مهر 46972 (مركز تستي براي كاربران سازمان)',
        centerType: 3,
        centerTypeDesc: 'آزمايشگاه',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8369111,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 105741,
        mcntMcntCnt: 105739,
        recipeType: 3,
        mcntName: 'ساخد',
        mcntTitle: ' آزمايشگاه  درمانگاه ساخد',
        centerType: 3,
        centerTypeDesc: 'آزمايشگاه',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8368235,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 47570,
        mcntMcntCnt: 47567,
        recipeType: 4,
        mcntName: 'بقيه اله',
        mcntTitle: ' مركز تصویربرداری  بيمارستان بقيه اله',
        centerType: 4,
        centerTypeDesc: 'مركز تصویربرداری',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'بوشهر',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8357485,
        hchrChr: 31,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 71172,
        mcntMcntCnt: null,
        recipeType: 4,
        mcntName: 'حسيني مهر 71172 (مركز تستي براي كاربران سازمان)',
        mcntTitle: ' مركز تصویربرداری  حسيني مهر 71172 (مركز تستي براي كاربران سازمان)',
        centerType: 4,
        centerTypeDesc: 'مركز تصویربرداری',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 4457172,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 105743,
        mcntMcntCnt: 105739,
        recipeType: 4,
        mcntName: 'ساخد',
        mcntTitle: ' مركز تصویربرداری  درمانگاه ساخد',
        centerType: 4,
        centerTypeDesc: 'مركز تصویربرداری',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8368236,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 120110,
        mcntMcntCnt: 120070,
        recipeType: 4,
        mcntName: 'مجرد',
        mcntTitle: ' مركز تصویربرداری  بيمارستان مجرد',
        centerType: 4,
        centerTypeDesc: 'مركز تصویربرداری',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 5034541,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 123798,
        mcntMcntCnt: 105057,
        recipeType: 10,
        mcntName: 'انصاري(شركت بيمارستان انصاري)',
        mcntTitle: ' مركزتوانبخشي  بيمارستان انصاري(شركت بيمارستان انصاري)',
        centerType: 5,
        centerTypeDesc: 'مركزتوانبخشي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8395963,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 122289,
        mcntMcntCnt: null,
        recipeType: 10,
        mcntName: 'محمد كريمي',
        mcntTitle: ' مركزتوانبخشي  محمد كريمي',
        centerType: 5,
        centerTypeDesc: 'مركزتوانبخشي',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'مازندران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8365534,
        hchrChr: 17,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 112382,
        mcntMcntCnt: 105739,
        recipeType: 10,
        mcntName: 'ساخد',
        mcntTitle: ' مركزتوانبخشي  درمانگاه ساخد',
        centerType: 5,
        centerTypeDesc: 'مركزتوانبخشي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8368232,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 120113,
        mcntMcntCnt: 120070,
        recipeType: 10,
        mcntName: 'مجرد',
        mcntTitle: ' مركزتوانبخشي  بيمارستان مجرد',
        centerType: 5,
        centerTypeDesc: 'مركزتوانبخشي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8342050,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 54031,
        mcntMcntCnt: 17159,
        recipeType: 5,
        mcntName: 'پيمانيه جهرم',
        mcntTitle: ' مركز بستري  بيمارستان پيمانيه جهرم',
        centerType: 6,
        centerTypeDesc: 'مركز بستري',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'فارس',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8362182,
        hchrChr: 32,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 39437,
        mcntMcntCnt: 39422,
        recipeType: 5,
        mcntName: 'شهيد چمران',
        mcntTitle: ' مركز بستري  بيمارستان شهيد چمران',
        centerType: 6,
        centerTypeDesc: 'مركز بستري',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6497189,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 97305,
        mcntMcntCnt: 71017,
        recipeType: 5,
        mcntName: 'خصوصي 30 درجه يك1',
        mcntTitle: ' مركز بستري  بيمارستان خصوصي 30 درجه يك1',
        centerType: 6,
        centerTypeDesc: 'مركز بستري',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6459804,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 43876,
        mcntMcntCnt: 43870,
        recipeType: 7,
        mcntName: 'پاكروان',
        mcntTitle: ' مركز خدمات پزشكي  درمانگاه پاكروان',
        centerType: 7,
        centerTypeDesc: 'مركز خدمات پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'قزوين',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6635243,
        hchrChr: 25,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 65141,
        mcntMcntCnt: 43870,
        recipeType: 7,
        mcntName: 'پاكروان / پايش سلامت',
        mcntTitle: ' مركز خدمات پزشكي  درمانگاه پاكروان / پايش سلامت',
        centerType: 7,
        centerTypeDesc: 'مركز خدمات پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'قزوين',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6635244,
        hchrChr: 25,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 40838,
        mcntMcntCnt: 40825,
        recipeType: 7,
        mcntName: 'بقيه الله اعظم',
        mcntTitle: ' مركز خدمات پزشكي  بيمارستان بقيه الله اعظم',
        centerType: 7,
        centerTypeDesc: 'مركز خدمات پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6462816,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 47572,
        mcntMcntCnt: 47567,
        recipeType: 7,
        mcntName: 'بقيه اله',
        mcntTitle: ' مركز خدمات پزشكي  بيمارستان بقيه اله',
        centerType: 7,
        centerTypeDesc: 'مركز خدمات پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'بوشهر',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6674535,
        hchrChr: 31,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 39674,
        mcntMcntCnt: 39642,
        recipeType: 7,
        mcntName: 'بقيه اله جماران(دانشگاه علوم پزشكي سپاه پاسداران)',
        mcntTitle: ' مركز خدمات پزشكي  بيمارستان بقيه اله جماران(دانشگاه علوم پزشكي سپاه پاسداران)',
        centerType: 7,
        centerTypeDesc: 'مركز خدمات پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6645418,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 104122,
        mcntMcntCnt: 104120,
        recipeType: 7,
        mcntName: 'دم (مراقبت هاي باليني در منزل)',
        mcntTitle: ' مركز خدمات پزشكي  درمانگاه دم (مراقبت هاي باليني در منزل)',
        centerType: 7,
        centerTypeDesc: 'مركز خدمات پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6673539,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 39440,
        mcntMcntCnt: 39422,
        recipeType: 7,
        mcntName: 'شهيد چمران',
        mcntTitle: ' مركز خدمات پزشكي  بيمارستان شهيد چمران',
        centerType: 7,
        centerTypeDesc: 'مركز خدمات پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6408079,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 109393,
        mcntMcntCnt: 108013,
        recipeType: 7,
        mcntName: 'مركزخدمات پزشكي تخصصي ابن سينا',
        mcntTitle: ' مركز خدمات پزشكي  درمانگاه مركزخدمات پزشكي تخصصي ابن سينا',
        centerType: 7,
        centerTypeDesc: 'مركز خدمات پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6507602,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 40187,
        mcntMcntCnt: 40173,
        recipeType: 7,
        mcntName: 'وليعصر ناجا 1',
        mcntTitle: ' مركز خدمات پزشكي  بيمارستان وليعصر ناجا 1',
        centerType: 7,
        centerTypeDesc: 'مركز خدمات پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 4549713,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 65492,
        mcntMcntCnt: 65487,
        recipeType: 7,
        mcntName: 'وليعصر ناجا 1 (پايش سلامت)',
        mcntTitle: ' مركز خدمات پزشكي  بيمارستان وليعصر ناجا 1 (پايش سلامت)',
        centerType: 7,
        centerTypeDesc: 'مركز خدمات پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 5033301,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 114688,
        mcntMcntCnt: 105739,
        recipeType: 7,
        mcntName: 'حسيني مهر 114688 (مركز تستي براي كاربران سازمان)',
        mcntTitle: ' مركز خدمات پزشكي  درمانگاه حسيني مهر 114688 (مركز تستي براي كاربران سازمان)',
        centerType: 7,
        centerTypeDesc: 'مركز خدمات پزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8342051,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 126126,
        mcntMcntCnt: 120070,
        recipeType: 7,
        mcntName: 'مجرد',
        mcntTitle: ' مركز خدمات پزشكي  بيمارستان مجرد',
        centerType: 7,
        centerTypeDesc: 'مركز خدمات پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6512650,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 70154,
        mcntMcntCnt: null,
        recipeType: 9,
        mcntName: 'عينك سازي بين الملل',
        mcntTitle: ' مركزلوازم پزشكي  عينك سازي بين الملل',
        centerType: 9,
        centerTypeDesc: 'مركزلوازم پزشكي',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'كرمان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6498104,
        hchrChr: 15,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 57669,
        mcntMcntCnt: null,
        recipeType: 9,
        mcntName: 'عينك سازي شهيد صدوقي - لغو از1/3/91',
        mcntTitle: ' مركزلوازم پزشكي  عينك سازي شهيد صدوقي - لغو از1/3/91',
        centerType: 9,
        centerTypeDesc: 'مركزلوازم پزشكي',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اصفهان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6412117,
        hchrChr: 13,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 90966,
        mcntMcntCnt: null,
        recipeType: 9,
        mcntName: 'كلينيك ارتزوپرتز پارس سينا',
        mcntTitle: ' مركزلوازم پزشكي  كلينيك ارتزوپرتز پارس سينا',
        centerType: 9,
        centerTypeDesc: 'مركزلوازم پزشكي',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'همدان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6498400,
        hchrChr: 38,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 57940,
        mcntMcntCnt: null,
        recipeType: 9,
        mcntName: 'حسيني مهر',
        mcntTitle: ' مركزلوازم پزشكي  حسيني مهر',
        centerType: 9,
        centerTypeDesc: 'مركزلوازم پزشكي',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6654257,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 120114,
        mcntMcntCnt: 120070,
        recipeType: 9,
        mcntName: 'مجرد',
        mcntTitle: ' مركزلوازم پزشكي  بيمارستان مجرد',
        centerType: 9,
        centerTypeDesc: 'مركزلوازم پزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 5034542,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 31170,
        mcntMcntCnt: 31166,
        recipeType: 8,
        mcntName: 'امام علي (دندانپزشكي ناجا)',
        mcntTitle: ' مطب دندانپزشكي  درمانگاه امام علي (دندانپزشكي ناجا)',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 8,
        hchrDesc: 'نامعتبر است',
        hchrDescParent: 'اداره كل هاي نامعتبر',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6637640,
        hchrChr: 10,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 110526,
        mcntMcntCnt: null,
        recipeType: 8,
        mcntName: 'آرش نوري خرم آباديان',
        mcntTitle: ' مطب دندانپزشكي  آرش نوري خرم آباديان',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8392165,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 117780,
        mcntMcntCnt: 117779,
        recipeType: 8,
        mcntName: 'آريو(ريحانه پاليزگير)',
        mcntTitle: ' مطب دندانپزشكي  درمانگاه آريو(ريحانه پاليزگير)',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6511273,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 17581,
        mcntMcntCnt: 13055,
        recipeType: 8,
        mcntName: 'ايثارگران تربت جام(امام جعفر صادق)',
        mcntTitle: ' مطب دندانپزشكي  درمانگاه ايثارگران تربت جام(امام جعفر صادق)',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'خراسان رضوي',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6655744,
        hchrChr: 54,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 32670,
        mcntMcntCnt: 22830,
        recipeType: 8,
        mcntName: 'بهداري امام حسين شاهين شهر',
        mcntTitle: ' مطب دندانپزشكي  درمانگاه بهداري امام حسين شاهين شهر',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'اصفهان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 3167388,
        hchrChr: 13,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 90936,
        mcntMcntCnt: 90935,
        recipeType: 8,
        mcntName: 'بهراد',
        mcntTitle: ' مطب دندانپزشكي  درمانگاه بهراد',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'البرز',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6621588,
        hchrChr: 57,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 31504,
        mcntMcntCnt: 24266,
        recipeType: 8,
        mcntName: 'بيمارستان شهيد صدوقي',
        mcntTitle: ' مطب دندانپزشكي  بيمارستان بيمارستان شهيد صدوقي',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 3,
        hchrDesc: 'اصفهان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6480470,
        hchrChr: 13,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 121488,
        mcntMcntCnt: 121487,
        recipeType: 8,
        mcntName: 'خيام',
        mcntTitle: ' مطب دندانپزشكي  درمانگاه خيام',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'آذربايجان شرقي',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6504557,
        hchrChr: 43,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 35886,
        mcntMcntCnt: 35837,
        recipeType: 8,
        mcntName: 'فاطمه زهرا - كوثر2',
        mcntTitle: ' مطب دندانپزشكي  درمانگاه فاطمه زهرا - كوثر2',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'اداره کل اسنادپزشکي تهران',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6669854,
        hchrChr: 56,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 123469,
        mcntMcntCnt: null,
        recipeType: 8,
        mcntName: 'فراست مرادي',
        mcntTitle: ' مطب دندانپزشكي  فراست مرادي',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'هرمزگان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8366372,
        hchrChr: 18,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 35252,
        mcntMcntCnt: 27965,
        recipeType: 8,
        mcntName: 'كلينيك بقائي',
        mcntTitle: ' مطب دندانپزشكي  درمانگاه كلينيك بقائي',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'خوزستان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6660037,
        hchrChr: 51,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 109536,
        mcntMcntCnt: 109534,
        recipeType: 8,
        mcntName: 'كلينيك دندانپزشكي لبخند ستاره',
        mcntTitle: ' مطب دندانپزشكي  درمانگاه كلينيك دندانپزشكي لبخند ستاره',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'اصفهان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 3168874,
        hchrChr: 13,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 123444,
        mcntMcntCnt: 123443,
        recipeType: 8,
        mcntName: 'محمدعلي رهنما آباده',
        mcntTitle: ' مطب دندانپزشكي  درمانگاه محمدعلي رهنما آباده',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'فارس',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8380319,
        hchrChr: 32,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 122578,
        mcntMcntCnt: null,
        recipeType: 8,
        mcntName: 'مرضيه مويدي',
        mcntTitle: ' مطب دندانپزشكي  مرضيه مويدي',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'بوشهر',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8379865,
        hchrChr: 31,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 35302,
        mcntMcntCnt: 28764,
        recipeType: 8,
        mcntName: 'نيروي انتظامي (اهواز)',
        mcntTitle: ' مطب دندانپزشكي  درمانگاه نيروي انتظامي (اهواز)',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 3,
        hchrDesc: 'خوزستان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6634938,
        hchrChr: 51,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 71824,
        mcntMcntCnt: null,
        recipeType: 8,
        mcntName: ' دندانپزشكي ساخد',
        mcntTitle: ' مطب دندانپزشكي   دندانپزشكي ساخد',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6639193,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 106138,
        mcntMcntCnt: 88922,
        recipeType: 8,
        mcntName: 'تستي ساخد',
        mcntTitle: ' مطب دندانپزشكي  درمانگاه تستي ساخد',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: 11,
        centerTypeParentDesc: 'درمانگاه',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6405329,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 71833,
        mcntMcntCnt: null,
        recipeType: 8,
        mcntName: 'حسيني مهر 71833 (مركز تستي براي كاربران سازمان)',
        mcntTitle: ' مطب دندانپزشكي  حسيني مهر 71833 (مركز تستي براي كاربران سازمان)',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8365532,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: 105788,
        mcntMcntCnt: 105787,
        recipeType: 8,
        mcntName: 'ساخد',
        mcntTitle: ' مطب دندانپزشكي  بيمارستان ساخد',
        centerType: 10,
        centerTypeDesc: 'مطب دندانپزشكي',
        centerTypeParent: 12,
        centerTypeParentDesc: 'بيمارستان',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 8368233,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: null,
        mcntMcntCnt: null,
        recipeType: 1,
        mcntName: null,
        mcntTitle: 'يزد ميبد',
        centerType: null,
        centerTypeDesc: '',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 4,
        hchrDesc: 'ميبد',
        hchrDescParent: 'يزد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6678116,
        hchrChr: 113,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: null,
        mcntMcntCnt: null,
        recipeType: 1,
        mcntName: null,
        mcntTitle: 'اداره کل اردبيل',
        centerType: null,
        centerTypeDesc: '',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'اردبيل',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6480706,
        hchrChr: 45,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: null,
        mcntMcntCnt: null,
        recipeType: 1,
        mcntName: null,
        mcntTitle: 'اداره کل خوزستان',
        centerType: null,
        centerTypeDesc: '',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 3,
        hchrDesc: 'خوزستان',
        hchrDescParent: 'اداره کل',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6619421,
        hchrChr: 51,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
      {
        uuid: null,
        mcntCnt: null,
        mcntMcntCnt: null,
        recipeType: 1,
        mcntName: null,
        mcntTitle: 'ستاد ساخد معاونت خدمات الكترونيك سلامت (خاس)',
        centerType: null,
        centerTypeDesc: '',
        centerTypeParent: null,
        centerTypeParentDesc: '',
        horlOrl: 2,
        hchrDesc: 'معاونت خدمات الكترونيك سلامت (خاس)',
        hchrDescParent: 'ستاد ساخد',
        susrHempEmp: 49381,
        hempUserName: 'MOHGHASEMI',
        suchUch: 6424379,
        hchrChr: 2,
        unitType: null,
        loginType: 2,
        msdmSdm: null,
      },
    ],
    total: -1,
  },
};
