export enum UkIconName {
    // manex
    MANEX = 'manex',
    DIAMOND = 'diamond',
    DIAMOND_FILLED = 'diamond_filled',
    // arrow
    ARROW_LEFT = 'ar_left',
    ARROW_TOP = 'ar_top',
    ARROW_RIGHT = 'ar_right',
    ARROW_DOWN = 'ar_down',
    // chev
    CHEV_LEFT = 'chev_left',
    CHEV_RIGHT = 'chev_right',
    // expand
    EXPAND_LEFT_LIGHT = 'expand_left_light',
    EXPAND_DOWN_LIGHT = 'expand_down_light',
    EXPAND_UP_LIGHT = 'expand_up_light',
    EXPAND_RIGHT_LIGHT = 'expand_right_light',
    // filled
    PROFILE = 'profile',
    PROFILE_FILLED = 'profile_filled',
    OFFLINE_SHOP = 'offline_shop',
    OFFLINE_SHOP_FILLED = 'offline_shop_filled',
    ONLINE_SHOP = 'online_shop',
    // others
    LIGHTNING = 'lightning',
    SEARCH_ALT_LIGHT = 'search_alt_light',
    SIGN_IN = 'sign_in',
    SORT_DOWN_LIGHT = 'sort_down_light',
    PLUS = 'plus',
    CLOSE_RING_LIGHT = 'close_ring_light',
    LOCATION = 'location',
    MAP = 'map',
    DISCOUNT = 'tag',
    CREDIT_CARD = 'credit_card',
    EYE_VIEW = 'eye_view',
    SHOPPING_CART = 'shopping_cart',
    FEEDBACK = 'feedback',
    INFO_LIGHT = 'info_light',
    TIME_LIGHT = 'time_light',
    CHECK_MARK = 'check_mark',
    CATEGORIES = 'categories',
    LOCK_FILL = 'lock_fill',
    PHONE_LIGHT = 'phone_light',
    ONLINE_PLUS = 'online_plus',
    OFFLINE_PLUS = 'offline_plus',
    VOUCHER_PLUS = 'voucher_plus',
    CLOSE = 'close',
    // MULTI_CASHOUT_PLUS_B = 'multi_cashout_plus_b',
    // MULTI_CASHOUT_PLUS_F = 'multi_cashout_plus_f',
    USER_FILL = 'user_fill',
    // MULTI_SEB_B = 'multi_sep_b',
    // MULTI_SEB_F = 'multi_sep_f',
    INSTAGRAM = 'instagram',
    TICKET = 'ticket',
    GIFT_LIGHT = 'gift_light',
    CIRCLE_RIGHT_ALT = 'circle_right_alt',
    EDIT = 'edit',
    EDIT_1 = 'edit1',
    PHONE = 'phone',
    CHECK_CIRCLE = 'check_circle',
    USER_CALL = 'support',
    HOME_LIGHT = 'home_light',
    TRASH_DELETE = 'trash_delete',
    SHARE = 'share',
    COPY = 'copy',
    CIRCLE = 'app_icon_circle',
    PIN_LOCATION = 'pin_location',
    PERCENT = 'percent_01',
    SHOP_LIGHT = 'building',
    FILTER = 'filter',
    LIST_BULLETS = 'list_bullets',
    DONE_CHECK = 'done_check',
    WALLET = 'wallet',
    BACK_ICON = 'back_icon',
    LOGOUT = 'logout',
    MINUS = 'minus',
}

export type IconName = `${UkIconName}`;
