export const dataGridConfig = {
  columns: [
    {
      field: 'id',
      header: 'ID',
      width: '80px',
      filterable: true,
      sortable: true,
      frozen: true,
    },
    {
      field: 'firstName',
      header: 'First Name',
      width: '120px',
      filterable: true,
      sortable: true,
    },
    {
      field: 'lastName',
      header: 'Last Name',
      width: '120px',
      filterable: true,
      sortable: true,
    },
    {
      field: 'email',
      header: 'Email',
      width: '200px',
      filterable: true,
      sortable: true,
    },
    {
      field: 'department',
      header: 'Department',
      width: '150px',
      filterable: true,
      sortable: true,
    },
    {
      field: 'role',
      header: 'Role',
      width: '120px',
      filterable: true,
      sortable: true,
    },
    {
      field: 'status',
      header: 'Status',
      width: '130px',
      type: 'text',
      filterable: true,
      sortable: true,
    },
    {
      field: 'salary',
      header: 'Salary',
      width: '120px',
      type: 'number',
      filterable: true,
      sortable: true,
    },
    {
      field: 'joinDate',
      header: 'Join Date',
      width: '130px',
      type: 'date',
      filterable: true,
      sortable: true,
    },
    {
      field: 'lastLogin',
      header: 'Last Login',
      width: '150px',
      type: 'date',
      filterable: true,
      sortable: true,
    },
  ],
  rowsPerPage: 10,
  rowsPerPageOptions: [5, 10, 25, 50, 100],
  paginator: true,
  selectionMode: 'single',
  showCurrentPageReport: true,
  currentPageReportTemplate: 'Showing {first} to {last} of {totalRecords} entries',
  resizableColumns: true,
  columnResizeMode: 'fit',
  reorderableColumns: true,
  scrollable: true,
  scrollHeight: '500px',
  filterMode: 'column',
};
